/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/cave_man_original.glb");
  return (
    <group ref={group} {...props} dispose={null} scale={0.5}>
      <group position={[0.88, 6.22, 0.47]} scale={0.33}>
        <mesh
          geometry={nodes.Sphere_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Sphere_2.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.003"]}
        position={[-0.04, 6.71, -0.02]}
        scale={1.5}
      />
      <group position={[0, 5.72, 0]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cube_3.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cube_4.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.004"]}
        position={[0.76, 5.64, -0.02]}
        rotation={[0, 0, -1.47]}
        scale={1.5}
      />
      <group position={[0.88, 6.22, -0.46]} scale={0.33}>
        <mesh
          geometry={nodes.Sphere001_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Sphere001_2.geometry}
          material={materials["Material.007"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cave_man_original.glb");
